services:
  - type: web
    name: kitchenos-backend
    env: python
    rootDir: backend_django
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && python manage.py seed_plans && python manage.py create_admin_if_needed && gunicorn kitchenos.wsgi:application --preload
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: kitchenos.settings_prod
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        value: https://kitchenos-frontend.vercel.app
      - key: CORS_ALLOWED_ORIGIN_REGEXES
        value: https://.*\.vercel\.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://kitchenos-frontend.vercel.app
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
      - key: BREVO_SMTP_PASSWORD
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
