services:
  - type: web
    name: kitchenos-backend
    env: python
    rootDir: backend_django
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && python manage.py seed_plans && python manage.py create_admin_if_needed && gunicorn kitchenos.wsgi:application --preload
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://kitchenos_trex_user:ezltdvQkgCPRs9UqaDBJqUQbdmEHmF4M@dpg-daf9j0v40ujc73a9n5ag-a/kitchenos_trex
      - key: DJANGO_SETTINGS_MODULE
        value: kitchenos.settings_prod
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        value: https://kitchenos-frontend.vercel.app
      - key: CORS_ALLOWED_ORIGIN_REGEXES
        value: https://.*\.vercel\.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://kitchenos-frontend.vercel.app
      - key: ADMIN_EMAIL
        value: admin@kitchenos.app
      - key: ADMIN_PASSWORD
        value: Admin123
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_URL
        value: your-cloudinary-url
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-api-secret
