"""
Django settings for kitchenos project.
Generated by 'django-admin startproject' using Django 3.2.25.
"""

import os
from pathlib import Path
import environ
import dj_database_url

# ============================================
# Optional MySQL compatibility for older setups.
# Don't fail local/production startup if PyMySQL is not installed.
# ============================================
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ModuleNotFoundError:
    pass

# ============================================
# BASE DIRECTORY
# ============================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================
# ENVIRONMENT VARIABLES
# ============================================
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ============================================
# SECURITY
# ============================================
SECRET_KEY = env('SECRET_KEY', default='django-insecure-your-secret-key-here')
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    'localhost',
    '127.0.0.1',
])

# Auto-append your hosting platform's hostname (Render sets RENDER_EXTERNAL_HOSTNAME,
# Railway sets RAILWAY_STATIC_URL, PythonAnywhere sets nothing — defaults are fine)
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)
_railway_url = os.environ.get('RAILWAY_STATIC_URL')
if _railway_url and _railway_url not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_url)

# ============================================
# INSTALLED APPS
# ============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Custom apps (created with startapp)
    'users',
    'tenants',
    'branches',
    'menu',
    'core',
    'orders',
]

# ============================================
# MIDDLEWARE
# ============================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← MUST be at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← serve static files on Railway
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================
# URL CONFIG
# ============================================
ROOT_URLCONF = 'kitchenos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kitchenos.wsgi.application'

# ============================================
# DATABASE
# Use PostgreSQL on Railway when DATABASE_URL is provided,
# otherwise keep SQLite for local development.
# ============================================
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    )
}

# ============================================
# PASSWORD VALIDATION
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# INTERNATIONALIZATION
# ============================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
BREVO_SMTP_HOST = env('BREVO_SMTP_HOST', default='smtp-relay.brevo.com')
BREVO_SMTP_PORT = env.int('BREVO_SMTP_PORT', default=587)
BREVO_SMTP_USER = env('BREVO_SMTP_USER', default='')
BREVO_SMTP_PASSWORD = env('BREVO_SMTP_PASSWORD', default='')
BREVO_FROM_EMAIL = env('BREVO_FROM_EMAIL', default='noreply@kitchenos.app')

# Add production-friendly host and frontend origin settings.
def _sanitize_allowed_origins(raw_values):
    sanitized = []
    for origin in raw_values:
        cleaned = str(origin).strip()
        if not cleaned:
            continue
        lower = cleaned.lower()
        if 'friespowered.net' in lower or 'cuisine.' in lower:
            continue
        if cleaned not in sanitized:
            sanitized.append(cleaned)
    return sanitized

FRONTEND_ORIGINS = _sanitize_allowed_origins(env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:5173',
    'http://localhost:5174',
    FRONTEND_URL,
]))
if FRONTEND_URL and FRONTEND_URL not in FRONTEND_ORIGINS:
    FRONTEND_ORIGINS.append(FRONTEND_URL)
if 'https://*.vercel.app' not in FRONTEND_ORIGINS:
    FRONTEND_ORIGINS.append('https://*.vercel.app')

CSRF_TRUSTED_ORIGINS = _sanitize_allowed_origins(env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:5173',
    'http://localhost:5174',
    FRONTEND_URL,
]))
if FRONTEND_URL and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
if 'https://*.vercel.app' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://*.vercel.app')

# ============================================
# STATIC FILES
# ============================================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = []

# ============================================
# MEDIA FILES (Uploads)
# ============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============================================
# DEFAULT AUTO FIELD
# ============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CUSTOM USER MODEL
# ============================================
AUTH_USER_MODEL = 'users.User'

# ============================================
# CORS (Cross-Origin Resource Sharing)
# ============================================
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS
CORS_ALLOW_CREDENTIALS = True

# ============================================
# REST FRAMEWORK & JWT (Django 3.2 compatible)
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
}