from django.urls import path
from . import views

urlpatterns = [
    path('health/', views.HealthCheckView.as_view(), name='health'),
    path('admin/stats/', views.AdminStatsView.as_view(), name='admin-stats'),
    path('admin/tenants/', views.AdminTenantListView.as_view(), name='admin-tenants'),
    path('admin/approvals/', views.AdminApprovalListView.as_view(), name='admin-approvals'),
    path('admin/approve/<int:pk>/', views.AdminApproveView.as_view(), name='admin-approve'),
    path('admin/reject/<int:pk>/', views.AdminRejectView.as_view(), name='admin-reject'),
    path('admin/payments/', views.AdminPaymentListView.as_view(), name='admin-payments'),
    path('admin/payments/approve/<int:pk>/', views.AdminPaymentApproveView.as_view(), name='admin-payment-approve'),
    path('admin/payments/reject/<int:pk>/', views.AdminPaymentRejectView.as_view(), name='admin-payment-reject'),
    path('admin/audit-logs/', views.AdminAuditLogView.as_view(), name='admin-audit-logs'),
    path('admin/settings/', views.AdminSettingsView.as_view(), name='admin-settings'),
    path('tenants/payments/', views.TenantPaymentHistoryView.as_view(), name='tenant-payments'),
    path('admin/subscriptions/', views.AdminSubscriptionListView.as_view(), name='admin-subscriptions'),
    path('admin/subscriptions/extend/<int:pk>/', views.AdminSubscriptionExtendView.as_view(), name='admin-subscription-extend'),
    path('admin/subscriptions/suspend/<int:pk>/', views.AdminSubscriptionSuspendView.as_view(), name='admin-subscription-suspend'),
    path('admin/subscriptions/cancel/<int:pk>/', views.AdminSubscriptionCancelView.as_view(), name='admin-subscription-cancel'),
    path('admin/payments/export/', views.AdminPaymentExportView.as_view(), name='admin-payment-export'),
    path('admin/payments/bulk-approve/', views.AdminBulkApproveView.as_view(), name='admin-bulk-approve'),
    path('admin/payments/bulk-reject/', views.AdminBulkRejectView.as_view(), name='admin-bulk-reject'),
    path('admin/tenants/suspend/<int:pk>/', views.AdminTenantSuspendView.as_view(), name='admin-tenant-suspend'),
    path('admin/tenants/activate/<int:pk>/', views.AdminTenantActivateView.as_view(), name='admin-tenant-activate'),
    path('admin/tenants/delete/<int:pk>/', views.AdminTenantDeleteView.as_view(), name='admin-tenant-delete'),
    path('admin/tenants/bulk-suspend/', views.AdminBulkTenantSuspendView.as_view(), name='admin-bulk-tenant-suspend'),
    path('admin/tenants/bulk-activate/', views.AdminBulkTenantActivateView.as_view(), name='admin-bulk-tenant-activate'),
    path('admin/tenants/bulk-delete/', views.AdminBulkTenantDeleteView.as_view(), name='admin-bulk-tenant-delete'),
    path('admin/subscriptions/bulk-extend/', views.AdminBulkSubscriptionExtendView.as_view(), name='admin-bulk-subscription-extend'),
    path('admin/subscriptions/bulk-suspend/', views.AdminBulkSubscriptionSuspendView.as_view(), name='admin-bulk-subscription-suspend'),
    path('admin/subscriptions/bulk-cancel/', views.AdminBulkSubscriptionCancelView.as_view(), name='admin-bulk-subscription-cancel'),
    path('admin/analytics/revenue/', views.AdminAnalyticsRevenueView.as_view(), name='admin-analytics-revenue'),
    path('admin/analytics/top-items/', views.AdminAnalyticsTopItemsView.as_view(), name='admin-analytics-top-items'),
    path('admin/analytics/top-branches/', views.AdminAnalyticsTopBranchesView.as_view(), name='admin-analytics-top-branches'),
    path('admin/analytics/order-status/', views.AdminAnalyticsOrderStatusView.as_view(), name='admin-analytics-order-status'),
    path('admin/analytics/subscriptions/', views.AdminAnalyticsSubscriptionView.as_view(), name='admin-analytics-subscriptions'),
]
